packages:
  - packages/*

catalogs:
  base:
    vite: 6.3.5
    typescript: 5.8.3
    '@types/node': 24.0.1
  react:
    react: 19.1.0
    react-dom: 19.1.0
    '@types/react': 19.1.2
    '@types/react-dom': 19.1.2
    '@vitejs/plugin-react': 4.4.1
  router:
    '@tanstack/react-router': 1.121.12
    '@tanstack/react-router-devtools': 1.121.12
    '@tanstack/router-devtools': 1.121.12
    '@tanstack/router-plugin': 1.121.13
  lint:
    '@eslint/js': 9.25.0
    'eslint': 9.25.0
    'eslint-plugin-react-hooks': 5.2.0
    'eslint-plugin-react-refresh': 0.4.19
    'globals': 16.0.0
    'typescript-eslint': 8.30.1
  state-management:
    'zustand': 5.0.5
  ui:
    '@radix-ui/react-slot': 1.2.3
    '@tailwindcss/vite': 4.1.10
    'class-variance-authority': 0.7.1
    'clsx': 2.1.1
    'lucide-react': 0.515.0
    'tailwind-merge': 3.3.1
    'autoprefixer': 10.4.21
    'postcss': 8.5.5
    'tailwindcss': 4.1.10
    'tw-animate-css': 1.3.4
